language: ruby
cache: bundler
rvm:
  - 2.5.5
services:
  - postgresql
script: 
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mv config/database.yml config/database.yml.original
  - cp config/database.yml.travis config/database.yml
