language: ruby
cache: bundler
rvm:
- 2.1.2
before_script:
  - mysql -e 'create database travis_ci_test;'
  - mv config/database.yml config/database.yml.original
  - cp config/database.yml.travis config/database.yml
