version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    container_name: tiny_blog
    hostname: tiny_blog
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    tmpfs: 
      - /app/tmp
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tiny_blog_dev
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - db
