version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    container_name: tiny_blog
    hostname: tiny_blog
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_NAME=tiny_blog_dev
      - DB_USER=postgres
    depends_on:
      - db
